export const countryCodes = [
    { code: '+1', acronym: 'US', name: 'United States' },
    { code: '+93', acronym: 'AF', name: 'Afghanistan' },
    { code: '+355', acronym: 'AL', name: 'Albania' },
    { code: '+213', acronym: 'DZ', name: 'Algeria' },
    { code: '+1', acronym: 'AS', name: 'American Samoa' },
    { code: '+376', acronym: 'AD', name: 'Andorra' },
    { code: '+244', acronym: 'AO', name: 'Angola' },
    { code: '+1', acronym: 'AI', name: 'Anguilla' },
    { code: '+1', acronym: 'AG', name: 'Antigua and Barbuda' },
    { code: '+54', acronym: 'AR', name: 'Argentina' },
    { code: '+374', acronym: 'AM', name: 'Armenia' },
    { code: '+297', acronym: 'AW', name: 'Aruba' },
    { code: '+61', acronym: 'AU', name: 'Australia' },
    { code: '+43', acronym: 'AT', name: 'Austria' },
    { code: '+994', acronym: 'AZ', name: 'Azerbaijan' },
    { code: '+1', acronym: 'BS', name: 'Bahamas' },
    { code: '+973', acronym: 'BH', name: 'Bahrain' },
    { code: '+880', acronym: 'BD', name: 'Bangladesh' },
    { code: '+1', acronym: 'BB', name: 'Barbados' },
    { code: '+375', acronym: 'BY', name: 'Belarus' },
    { code: '+32', acronym: 'BE', name: 'Belgium' },
    { code: '+501', acronym: 'BZ', name: 'Belize' },
    { code: '+229', acronym: 'BJ', name: 'Benin' },
    { code: '+1', acronym: 'BM', name: 'Bermuda' },
    { code: '+975', acronym: 'BT', name: 'Bhutan' },
    { code: '+591', acronym: 'BO', name: 'Bolivia' },
    { code: '+387', acronym: 'BA', name: 'Bosnia and Herzegovina' },
    { code: '+267', acronym: 'BW', name: 'Botswana' },
    { code: '+55', acronym: 'BR', name: 'Brazil' },
    { code: '+1', acronym: 'IO', name: 'British Indian Ocean Territory' },
    { code: '+673', acronym: 'BN', name: 'Brunei Darussalam' },
    { code: '+359', acronym: 'BG', name: 'Bulgaria' },
    { code: '+226', acronym: 'BF', name: 'Burkina Faso' },
    { code: '+257', acronym: 'BI', name: 'Burundi' },
    { code: '+855', acronym: 'KH', name: 'Cambodia' },
    { code: '+237', acronym: 'CM', name: 'Cameroon' },
    { code: '+1', acronym: 'CA', name: 'Canada' },
    { code: '+238', acronym: 'CV', name: 'Cape Verde' },
    { code: '+345', acronym: 'KY', name: 'Cayman Islands' },
    { code: '+236', acronym: 'CF', name: 'Central African Republic' },
    { code: '+61', acronym: 'CC', name: 'Christmas Island' },
    { code: '+61', acronym: 'CX', name: 'Cocos (Keeling) Islands' },
    { code: '+57', acronym: 'CO', name: 'Colombia' },
    { code: '+269', acronym: 'KM', name: 'Comoros' },
    { code: '+242', acronym: 'CG', name: 'Congo' },
    { code: '+243', acronym: 'CD', name: 'Congo, Democratic Republic of the' },
    { code: '+682', acronym: 'CK', name: 'Cook Islands' },
    { code: '+506', acronym: 'CR', name: 'Costa Rica' },
    { code: '+225', acronym: 'CI', name: 'Côte d\'Ivoire' },
    { code: '+385', acronym: 'HR', name: 'Croatia' },
    { code: '+53', acronym: 'CU', name: 'Cuba' },
    { code: '+599', acronym: 'CW', name: 'Curaçao' },
    { code: '+357', acronym: 'CY', name: 'Cyprus' },
    { code: '+420', acronym: 'CZ', name: 'Czech Republic' },
    { code: '+45', acronym: 'DK', name: 'Denmark' },
    { code: '+253', acronym: 'DJ', name: 'Djibouti' },
    { code: '+1', acronym: 'DM', name: 'Dominica' },
    { code: '+1809', acronym: 'DO', name: 'Dominican Republic' },
    { code: '+670', acronym: 'TL', name: 'Timor-Leste' },
    { code: '+593', acronym: 'EC', name: 'Ecuador' },
    { code: '+20', acronym: 'EG', name: 'Egypt' },
    { code: '+503', acronym: 'SV', name: 'El Salvador' },
    { code: '+240', acronym: 'GQ', name: 'Equatorial Guinea' },
    { code: '+291', acronym: 'ER', name: 'Eritrea' },
    { code: '+372', acronym: 'EE', name: 'Estonia' },
    { code: '+251', acronym: 'ET', name: 'Ethiopia' },
    { code: '+500', acronym: 'FK', name: 'Falkland Islands (Malvinas)' },
    { code: '+298', acronym: 'FO', name: 'Faroe Islands' },
    { code: '+679', acronym: 'FJ', name: 'Fiji' },
    { code: '+358', acronym: 'FI', name: 'Finland' },
    { code: '+33', acronym: 'FR', name: 'France' },
    { code: '+594', acronym: 'GF', name: 'French Guiana' },
    { code: '+689', acronym: 'PF', name: 'French Polynesia' },
    { code: '+241', acronym: 'GA', name: 'Gabon' },
    { code: '+220', acronym: 'GM', name: 'Gambia' },
    { code: '+995', acronym: 'GE', name: 'Georgia' },
    { code: '+49', acronym: 'DE', name: 'Germany' },
    { code: '+233', acronym: 'GH', name: 'Ghana' },
    { code: '+350', acronym: 'GI', name: 'Gibraltar' },
    { code: '+30', acronym: 'GR', name: 'Greece' },
    { code: '+299', acronym: 'GL', name: 'Greenland' },
    { code: '+1', acronym: 'GD', name: 'Grenada' },
    { code: '+590', acronym: 'GP', name: 'Guadeloupe' },
    { code: '+1', acronym: 'GU', name: 'Guam' },
    { code: '+502', acronym: 'GT', name: 'Guatemala' },
    { code: '+44', acronym: 'GG', name: 'Guernsey' },
    { code: '+224', acronym: 'GN', name: 'Guinea' },
    { code: '+245', acronym: 'GW', name: 'Guinea-Bissau' },
    { code: '+595', acronym: 'GY', name: 'Guyana' },
    { code: '+509', acronym: 'HT', name: 'Haiti' },
    { code: '+504', acronym: 'HN', name: 'Honduras' },
    { code: '+852', acronym: 'HK', name: 'Hong Kong' },
    { code: '+36', acronym: 'HU', name: 'Hungary' },
    { code: '+354', acronym: 'IS', name: 'Iceland' },
    { code: '+91', acronym: 'IN', name: 'India' },
    { code: '+62', acronym: 'ID', name: 'Indonesia' },
    { code: '+98', acronym: 'IR', name: 'Iran' },
    { code: '+964', acronym: 'IQ', name: 'Iraq' },
    { code: '+353', acronym: 'IE', name: 'Ireland' },
    { code: '+44', acronym: 'IM', name: 'Isle of Man' },
    { code: '+972', acronym: 'IL', name: 'Israel' },
    { code: '+39', acronym: 'IT', name: 'Italy' },
    { code: '+1', acronym: 'JM', name: 'Jamaica' },
    { code: '+81', acronym: 'JP', name: 'Japan' },
    { code: '+44', acronym: 'JE', name: 'Jersey' },
    { code: '+962', acronym: 'JO', name: 'Jordan' },
    { code: '+7', acronym: 'KZ', name: 'Kazakhstan' },
    { code: '+254', acronym: 'KE', name: 'Kenya' },
    { code: '+686', acronym: 'KI', name: 'Kiribati' },
    { code: '+383', acronym: 'XK', name: 'Kosovo' },
    { code: '+965', acronym: 'KW', name: 'Kuwait' },
    { code: '+996', acronym: 'KG', name: 'Kyrgyzstan' },
    { code: '+856', acronym: 'LA', name: 'Lao People\'s Democratic Republic' },
    { code: '+371', acronym: 'LV', name: 'Latvia' },
    { code: '+961', acronym: 'LB', name: 'Lebanon' },
    { code: '+266', acronym: 'LS', name: 'Lesotho' },
    { code: '+231', acronym: 'LR', name: 'Liberia' },
    { code: '+218', acronym: 'LY', name: 'Libya' },
    { code: '+423', acronym: 'LI', name: 'Liechtenstein' },
    { code: '+370', acronym: 'LT', name: 'Lithuania' },
    { code: '+352', acronym: 'LU', name: 'Luxembourg' },
    { code: '+261', acronym: 'MG', name: 'Madagascar' },
    { code: '+265', acronym: 'MW', name: 'Malawi' },
    { code: '+60', acronym: 'MY', name: 'Malaysia' },
    { code: '+960', acronym: 'MV', name: 'Maldives' },
    { code: '+223', acronym: 'ML', name: 'Mali' },
    { code: '+356', acronym: 'MT', name: 'Malta' },
    { code: '+692', acronym: 'MH', name: 'Marshall Islands' },
    { code: '+596', acronym: 'MQ', name: 'Martinique' },
    { code: '+222', acronym: 'MR', name: 'Mauritania' },
    { code: '+230', acronym: 'MU', name: 'Mauritius' },
    { code: '+262', acronym: 'RE', name: 'Réunion' },
    { code: '+52', acronym: 'MX', name: 'Mexico' },
    { code: '+691', acronym: 'FM', name: 'Micronesia' },
    { code: '+373', acronym: 'MD', name: 'Moldova' },
    { code: '+377', acronym: 'MC', name: 'Monaco' },
    { code: '+976', acronym: 'MN', name: 'Mongolia' },
    { code: '+382', acronym: 'ME', name: 'Montenegro' },
    { code: '+1664', acronym: 'MS', name: 'Montserrat' },
    { code: '+212', acronym: 'MA', name: 'Morocco' },
    { code: '+258', acronym: 'MZ', name: 'Mozambique' },
    { code: '+95', acronym: 'MM', name: 'Myanmar' },
    { code: '+264', acronym: 'NA', name: 'Namibia' },
    { code: '+674', acronym: 'NR', name: 'Nauru' },
    { code: '+977', acronym: 'NP', name: 'Nepal' },
    { code: '+31', acronym: 'NL', name: 'Netherlands' },
    { code: '+599', acronym: 'AN', name: 'Netherlands Antilles' },
    { code: '+64', acronym: 'NZ', name: 'New Zealand' },
    { code: '+505', acronym: 'NI', name: 'Nicaragua' },
    { code: '+227', acronym: 'NE', name: 'Niger' },
    { code: '+234', acronym: 'NG', name: 'Nigeria' },
    { code: '+683', acronym: 'NU', name: 'Niue' },
    { code: '+672', acronym: 'NF', name: 'Norfolk Island' },
    { code: '+1', acronym: 'MP', name: 'Northern Mariana Islands' },
    { code: '+47', acronym: 'NO', name: 'Norway' },
    { code: '+968', acronym: 'OM', name: 'Oman' },
    { code: '+92', acronym: 'PK', name: 'Pakistan' },
    { code: '+680', acronym: 'PW', name: 'Palau' },
    { code: '+970', acronym: 'PS', name: 'Palestine, State of' },
    { code: '+507', acronym: 'PA', name: 'Panama' },
    { code: '+675', acronym: 'PG', name: 'Papua New Guinea' },
    { code: '+595', acronym: 'PY', name: 'Paraguay' },
    { code: '+51', acronym: 'PE', name: 'Peru' },
    { code: '+63', acronym: 'PH', name: 'Philippines' },
    { code: '+48', acronym: 'PL', name: 'Poland' },
    { code: '+351', acronym: 'PT', name: 'Portugal' },
    { code: '+1', acronym: 'PR', name: 'Puerto Rico' },
    { code: '+974', acronym: 'QA', name: 'Qatar' },
    { code: '+262', acronym: 'RE', name: 'Réunion' },
    { code: '+40', acronym: 'RO', name: 'Romania' },
    { code: '+7', acronym: 'RU', name: 'Russian Federation' },
    { code: '+250', acronym: 'RW', name: 'Rwanda' },
    { code: '+508', acronym: 'PM', name: 'Saint Pierre and Miquelon' },
    { code: '+1784', acronym: 'VC', name: 'Saint Vincent and the Grenadines' },
    { code: '+1', acronym: 'WS', name: 'Samoa' },
    { code: '+685', acronym: 'SM', name: 'San Marino' },
    { code: '+239', acronym: 'ST', name: 'Sao Tome and Principe' },
    { code: '+966', acronym: 'SA', name: 'Saudi Arabia' },
    { code: '+221', acronym: 'SN', name: 'Senegal' },
    { code: '+381', acronym: 'RS', name: 'Serbia' },
    { code: '+248', acronym: 'SC', name: 'Seychelles' },
    { code: '+232', acronym: 'SL', name: 'Sierra Leone' },
    { code: '+65', acronym: 'SG', name: 'Singapore' },
    { code: '+421', acronym: 'SK', name: 'Slovakia' },
    { code: '+386', acronym: 'SI', name: 'Slovenia' },
    { code: '+677', acronym: 'SB', name: 'Solomon Islands' },
    { code: '+252', acronym: 'SO', name: 'Somalia' },
    { code: '+27', acronym: 'ZA', name: 'South Africa' },
    { code: '+82', acronym: 'KR', name: 'South Korea' },
    { code: '+211', acronym: 'SS', name: 'South Sudan' },
    { code: '+34', acronym: 'ES', name: 'Spain' },
    { code: '+94', acronym: 'LK', name: 'Sri Lanka' },
    { code: '+249', acronym: 'SD', name: 'Sudan' },
    { code: '+597', acronym: 'SR', name: 'Suriname' },
    { code: '+268', acronym: 'SZ', name: 'Swaziland' },
    { code: '+46', acronym: 'SE', name: 'Sweden' },
    { code: '+41', acronym: 'CH', name: 'Switzerland' },
    { code: '+963', acronym: 'SY', name: 'Syrian Arab Republic' },
    { code: '+886', acronym: 'TW', name: 'Taiwan' },
    { code: '+992', acronym: 'TJ', name: 'Tajikistan' },
    { code: '+255', acronym: 'TZ', name: 'Tanzania' },
    { code: '+66', acronym: 'TH', name: 'Thailand' },
    { code: '+228', acronym: 'TG', name: 'Togo' },
    { code: '+690', acronym: 'TK', name: 'Tokelau' },
    { code: '+676', acronym: 'TO', name: 'Tonga' },
    { code: '+1', acronym: 'TT', name: 'Trinidad and Tobago' },
    { code: '+216', acronym: 'TN', name: 'Tunisia' },
    { code: '+90', acronym: 'TR', name: 'Turkey' },
    { code: '+993', acronym: 'TM', name: 'Turkmenistan' },
    { code: '+1', acronym: 'TC', name: 'Turks and Caicos Islands' },
    { code: '+688', acronym: 'TV', name: 'Tuvalu' },
    { code: '+256', acronym: 'UG', name: 'Uganda' },
    { code: '+380', acronym: 'UA', name: 'Ukraine' },
    { code: '+971', acronym: 'AE', name: 'United Arab Emirates' },
    { code: '+44', acronym: 'GB', name: 'United Kingdom' },
    { code: '+598', acronym: 'UY', name: 'Uruguay' },
    { code: '+998', acronym: 'UZ', name: 'Uzbekistan' },
    { code: '+678', acronym: 'VU', name: 'Vanuatu' },
    { code: '+39', acronym: 'VA', name: 'Vatican City' },
    { code: '+58', acronym: 'VE', name: 'Venezuela' },
    { code: '+84', acronym: 'VN', name: 'Vietnam' },
    { code: '+681', acronym: 'WF', name: 'Wallis and Futuna' },
    { code: '+967', acronym: 'YE', name: 'Yemen' },
    { code: '+260', acronym: 'ZM', name: 'Zambia' },
    { code: '+263', acronym: 'ZW', name: 'Zimbabwe' }
  ];
  