export const countryCodes = [
  { "name": "Afghanistan", "iso2": "af", "dialCode": "+93", "flag": "https://flagcdn.com/w320/af.png" },
  { "name": "Albania", "iso2": "al", "dialCode": "+355", "flag": "https://flagcdn.com/w320/al.png" },
  { "name": "Algeria", "iso2": "dz", "dialCode": "+213", "flag": "https://flagcdn.com/w320/dz.png" },
  { "name": "Andorra", "iso2": "ad", "dialCode": "+376", "flag": "https://flagcdn.com/w320/ad.png" },
  { "name": "Angola", "iso2": "ao", "dialCode": "+244", "flag": "https://flagcdn.com/w320/ao.png" },
  { "name": "Argentina", "iso2": "ar", "dialCode": "+54", "flag": "https://flagcdn.com/w320/ar.png" },
  { "name": "Armenia", "iso2": "am", "dialCode": "+374", "flag": "https://flagcdn.com/w320/am.png" },
  { "name": "Australia", "iso2": "au", "dialCode": "+61", "flag": "https://flagcdn.com/w320/au.png" },
  { "name": "Austria", "iso2": "at", "dialCode": "+43", "flag": "https://flagcdn.com/w320/at.png" },
  { "name": "Azerbaijan", "iso2": "az", "dialCode": "+994", "flag": "https://flagcdn.com/w320/az.png" },
  { "name": "Bahrain", "iso2": "bh", "dialCode": "+973", "flag": "https://flagcdn.com/w320/bh.png" },
  { "name": "Bangladesh", "iso2": "bd", "dialCode": "+880", "flag": "https://flagcdn.com/w320/bd.png" },
  { "name": "Belarus", "iso2": "by", "dialCode": "+375", "flag": "https://flagcdn.com/w320/by.png" },
  { "name": "Belgium", "iso2": "be", "dialCode": "+32", "flag": "https://flagcdn.com/w320/be.png" },
  { "name": "Belize", "iso2": "bz", "dialCode": "+501", "flag": "https://flagcdn.com/w320/bz.png" },
  { "name": "Benin", "iso2": "bj", "dialCode": "+229", "flag": "https://flagcdn.com/w320/bj.png" },
  { "name": "Bhutan", "iso2": "bt", "dialCode": "+975", "flag": "https://flagcdn.com/w320/bt.png" },
  { "name": "Bolivia", "iso2": "bo", "dialCode": "+591", "flag": "https://flagcdn.com/w320/bo.png" },
  { "name": "Bosnia and Herzegovina", "iso2": "ba", "dialCode": "+387", "flag": "https://flagcdn.com/w320/ba.png" },
  { "name": "Botswana", "iso2": "bw", "dialCode": "+267", "flag": "https://flagcdn.com/w320/bw.png" },
  { "name": "Brazil", "iso2": "br", "dialCode": "+55", "flag": "https://flagcdn.com/w320/br.png" },
  { "name": "Brunei", "iso2": "bn", "dialCode": "+673", "flag": "https://flagcdn.com/w320/bn.png" },
  { "name": "Bulgaria", "iso2": "bg", "dialCode": "+359", "flag": "https://flagcdn.com/w320/bg.png" },
  { "name": "Burkina Faso", "iso2": "bf", "dialCode": "+226", "flag": "https://flagcdn.com/w320/bf.png" },
  { "name": "Burundi", "iso2": "bi", "dialCode": "+257", "flag": "https://flagcdn.com/w320/bi.png" },
  { "name": "Cambodia", "iso2": "kh", "dialCode": "+855", "flag": "https://flagcdn.com/w320/kh.png" },
  { "name": "Cameroon", "iso2": "cm", "dialCode": "+237", "flag": "https://flagcdn.com/w320/cm.png" },
  { "name": "Canada", "iso2": "ca", "dialCode": "+1", "flag": "https://flagcdn.com/w320/ca.png" },
  { "name": "Cape Verde", "iso2": "cv", "dialCode": "+238", "flag": "https://flagcdn.com/w320/cv.png" },
  { "name": "Chad", "iso2": "td", "dialCode": "+235", "flag": "https://flagcdn.com/w320/td.png" },
  { "name": "Chile", "iso2": "cl", "dialCode": "+56", "flag": "https://flagcdn.com/w320/cl.png" },
  { "name": "China", "iso2": "cn", "dialCode": "+86", "flag": "https://flagcdn.com/w320/cn.png" },
  { "name": "Colombia", "iso2": "co", "dialCode": "+57", "flag": "https://flagcdn.com/w320/co.png" },
  { "name": "Congo", "iso2": "cg", "dialCode": "+242", "flag": "https://flagcdn.com/w320/cg.png" },
  { "name": "Costa Rica", "iso2": "cr", "dialCode": "+506", "flag": "https://flagcdn.com/w320/cr.png" },
  { "name": "Croatia", "iso2": "hr", "dialCode": "+385", "flag": "https://flagcdn.com/w320/hr.png" },
  { "name": "Cuba", "iso2": "cu", "dialCode": "+53", "flag": "https://flagcdn.com/w320/cu.png" },
  { "name": "Cyprus", "iso2": "cy", "dialCode": "+357", "flag": "https://flagcdn.com/w320/cy.png" },
  { "name": "Czech Republic", "iso2": "cz", "dialCode": "+420", "flag": "https://flagcdn.com/w320/cz.png" },
  { "name": "Denmark", "iso2": "dk", "dialCode": "+45", "flag": "https://flagcdn.com/w320/dk.png" },
  { "name": "Djibouti", "iso2": "dj", "dialCode": "+253", "flag": "https://flagcdn.com/w320/dj.png" },
  { "name": "Dominican Republic", "iso2": "do", "dialCode": "+1", "flag": "https://flagcdn.com/w320/do.png" },
  { "name": "Ecuador", "iso2": "ec", "dialCode": "+593", "flag": "https://flagcdn.com/w320/ec.png" },
  { "name": "Egypt", "iso2": "eg", "dialCode": "+20", "flag": "https://flagcdn.com/w320/eg.png" },
  { "name": "El Salvador", "iso2": "sv", "dialCode": "+503", "flag": "https://flagcdn.com/w320/sv.png" },
  { "name": "Estonia", "iso2": "ee", "dialCode": "+372", "flag": "https://flagcdn.com/w320/ee.png" },
  { "name": "Ethiopia", "iso2": "et", "dialCode": "+251", "flag": "https://flagcdn.com/w320/et.png" },
  { "name": "Fiji", "iso2": "fj", "dialCode": "+679", "flag": "https://flagcdn.com/w320/fj.png" },
  { "name": "Finland", "iso2": "fi", "dialCode": "+358", "flag": "https://flagcdn.com/w320/fi.png" },
  { "name": "France", "iso2": "fr", "dialCode": "+33", "flag": "https://flagcdn.com/w320/fr.png" },
  { "name": "Gabon", "iso2": "ga", "dialCode": "+241", "flag": "https://flagcdn.com/w320/ga.png" },
  { "name": "Gambia", "iso2": "gm", "dialCode": "+220", "flag": "https://flagcdn.com/w320/gm.png" },
  { "name": "Georgia", "iso2": "ge", "dialCode": "+995", "flag": "https://flagcdn.com/w320/ge.png" },
  { "name": "Germany", "iso2": "de", "dialCode": "+49", "flag": "https://flagcdn.com/w320/de.png" },
  { "name": "Ghana", "iso2": "gh", "dialCode": "+233", "flag": "https://flagcdn.com/w320/gh.png" },
  { "name": "Greece", "iso2": "gr", "dialCode": "+30", "flag": "https://flagcdn.com/w320/gr.png" },
  { "name": "Grenada", "iso2": "gd", "dialCode": "+1", "flag": "https://flagcdn.com/w320/gd.png" },
  { "name": "Guatemala", "iso2": "gt", "dialCode": "+502", "flag": "https://flagcdn.com/w320/gt.png" },
  { "name": "Haiti", "iso2": "ht", "dialCode": "+509", "flag": "https://flagcdn.com/w320/ht.png" },
  { "name": "Honduras", "iso2": "hn", "dialCode": "+504", "flag": "https://flagcdn.com/w320/hn.png" },
  { "name": "Hungary", "iso2": "hu", "dialCode": "+36", "flag": "https://flagcdn.com/w320/hu.png" },
  { "name": "Iceland", "iso2": "is", "dialCode": "+354", "flag": "https://flagcdn.com/w320/is.png" },
  { "name": "India", "iso2": "in", "dialCode": "+91", "flag": "https://flagcdn.com/w320/in.png" },
  { "name": "Indonesia", "iso2": "id", "dialCode": "+62", "flag": "https://flagcdn.com/w320/id.png" },
  { "name": "Iran", "iso2": "ir", "dialCode": "+98", "flag": "https://flagcdn.com/w320/ir.png" },
  { "name": "Iraq", "iso2": "iq", "dialCode": "+964", "flag": "https://flagcdn.com/w320/iq.png" },
  { "name": "Ireland", "iso2": "ie", "dialCode": "+353", "flag": "https://flagcdn.com/w320/ie.png" },
  { "name": "Israel", "iso2": "il", "dialCode": "+972", "flag": "https://flagcdn.com/w320/il.png" },
  { "name": "Italy", "iso2": "it", "dialCode": "+39", "flag": "https://flagcdn.com/w320/it.png" },
  { "name": "Ivory Coast", "iso2": "ci", "dialCode": "+225", "flag": "https://flagcdn.com/w320/ci.png" },
  { "name": "Jamaica", "iso2": "jm", "dialCode": "+1", "flag": "https://flagcdn.com/w320/jm.png" },
  { "name": "Japan", "iso2": "jp", "dialCode": "+81", "flag": "https://flagcdn.com/w320/jp.png" },
  { "name": "Jordan", "iso2": "jo", "dialCode": "+962", "flag": "https://flagcdn.com/w320/jo.png" },
  { "name": "Kazakhstan", "iso2": "kz", "dialCode": "+7", "flag": "https://flagcdn.com/w320/kz.png" },
  { "name": "Kenya", "iso2": "ke", "dialCode": "+254", "flag": "https://flagcdn.com/w320/ke.png" },
  { "name": "Kuwait", "iso2": "kw", "dialCode": "+965", "flag": "https://flagcdn.com/w320/kw.png" },
  { "name": "Kyrgyzstan", "iso2": "kg", "dialCode": "+996", "flag": "https://flagcdn.com/w320/kg.png" },
  { "name": "Laos", "iso2": "la", "dialCode": "+856", "flag": "https://flagcdn.com/w320/la.png" },
  { "name": "Latvia", "iso2": "lv", "dialCode": "+371", "flag": "https://flagcdn.com/w320/lv.png" },
  { "name": "Lebanon", "iso2": "lb", "dialCode": "+961", "flag": "https://flagcdn.com/w320/lb.png" },
  { "name": "Lesotho", "iso2": "ls", "dialCode": "+266", "flag": "https://flagcdn.com/w320/ls.png" },
  { "name": "Liberia", "iso2": "lr", "dialCode": "+231", "flag": "https://flagcdn.com/w320/lr.png" },
  { "name": "Libya", "iso2": "ly", "dialCode": "+218", "flag": "https://flagcdn.com/w320/ly.png" },
  { "name": "Lithuania", "iso2": "lt", "dialCode": "+370", "flag": "https://flagcdn.com/w320/lt.png" },
  { "name": "Luxembourg", "iso2": "lu", "dialCode": "+352", "flag": "https://flagcdn.com/w320/lu.png" },
  { "name": "Madagascar", "iso2": "mg", "dialCode": "+261", "flag": "https://flagcdn.com/w320/mg.png" },
  { "name": "Malawi", "iso2": "mw", "dialCode": "+265", "flag": "https://flagcdn.com/w320/mw.png" },
  { "name": "Malaysia", "iso2": "my", "dialCode": "+60", "flag": "https://flagcdn.com/w320/my.png" },
  { "name": "Maldives", "iso2": "mv", "dialCode": "+960", "flag": "https://flagcdn.com/w320/mv.png" },
  { "name": "Mali", "iso2": "ml", "dialCode": "+223", "flag": "https://flagcdn.com/w320/ml.png" },
  { "name": "Malta", "iso2": "mt", "dialCode": "+356", "flag": "https://flagcdn.com/w320/mt.png" },
  { "name": "Mauritania", "iso2": "mr", "dialCode": "+222", "flag": "https://flagcdn.com/w320/mr.png" },
  { "name": "Mauritius", "iso2": "mu", "dialCode": "+230", "flag": "https://flagcdn.com/w320/mu.png" },
  { "name": "Mexico", "iso2": "mx", "dialCode": "+52", "flag": "https://flagcdn.com/w320/mx.png" },
  { "name": "Moldova", "iso2": "md", "dialCode": "+373", "flag": "https://flagcdn.com/w320/md.png" },
  { "name": "Monaco", "iso2": "mc", "dialCode": "+377", "flag": "https://flagcdn.com/w320/mc.png" },
  { "name": "Mongolia", "iso2": "mn", "dialCode": "+976", "flag": "https://flagcdn.com/w320/mn.png" },
  { "name": "Montenegro", "iso2": "me", "dialCode": "+382", "flag": "https://flagcdn.com/w320/me.png" },
  { "name": "Morocco", "iso2": "ma", "dialCode": "+212", "flag": "https://flagcdn.com/w320/ma.png" },
  { "name": "Mozambique", "iso2": "mz", "dialCode": "+258", "flag": "https://flagcdn.com/w320/mz.png" },
  { "name": "Myanmar", "iso2": "mm", "dialCode": "+95", "flag": "https://flagcdn.com/w320/mm.png" },
  { "name": "Namibia", "iso2": "na", "dialCode": "+264", "flag": "https://flagcdn.com/w320/na.png" },
  { "name": "Nepal", "iso2": "np", "dialCode": "+977", "flag": "https://flagcdn.com/w320/np.png" },
  { "name": "Netherlands", "iso2": "nl", "dialCode": "+31", "flag": "https://flagcdn.com/w320/nl.png" },
  { "name": "New Zealand", "iso2": "nz", "dialCode": "+64", "flag": "https://flagcdn.com/w320/nz.png" },
  { "name": "Nicaragua", "iso2": "ni", "dialCode": "+505", "flag": "https://flagcdn.com/w320/ni.png" },
  { "name": "Niger", "iso2": "ne", "dialCode": "+227", "flag": "https://flagcdn.com/w320/ne.png" },
  { "name": "Nigeria", "iso2": "ng", "dialCode": "+234", "flag": "https://flagcdn.com/w320/ng.png" },
  { "name": "Norway", "iso2": "no", "dialCode": "+47", "flag": "https://flagcdn.com/w320/no.png" },
  { "name": "Oman", "iso2": "om", "dialCode": "+968", "flag": "https://flagcdn.com/w320/om.png" },
  { "name": "Pakistan", "iso2": "pk", "dialCode": "+92", "flag": "https://flagcdn.com/w320/pk.png" },
  { "name": "Palestine", "iso2": "ps", "dialCode": "+970", "flag": "https://flagcdn.com/w320/ps.png" },
  { "name": "Panama", "iso2": "pa", "dialCode": "+507", "flag": "https://flagcdn.com/w320/pa.png" },
  { "name": "Paraguay", "iso2": "py", "dialCode": "+595", "flag": "https://flagcdn.com/w320/py.png" },
  { "name": "Peru", "iso2": "pe", "dialCode": "+51", "flag": "https://flagcdn.com/w320/pe.png" },
  { "name": "Philippines", "iso2": "ph", "dialCode": "+63", "flag": "https://flagcdn.com/w320/ph.png" },
  { "name": "Poland", "iso2": "pl", "dialCode": "+48", "flag": "https://flagcdn.com/w320/pl.png" },
  { "name": "Portugal", "iso2": "pt", "dialCode": "+351", "flag": "https://flagcdn.com/w320/pt.png" },
  { "name": "Qatar", "iso2": "qa", "dialCode": "+974", "flag": "https://flagcdn.com/w320/qa.png" },
  { "name": "Romania", "iso2": "ro", "dialCode": "+40", "flag": "https://flagcdn.com/w320/ro.png" },
  { "name": "Russia", "iso2": "ru", "dialCode": "+7", "flag": "https://flagcdn.com/w320/ru.png" },
  { "name": "Rwanda", "iso2": "rw", "dialCode": "+250", "flag": "https://flagcdn.com/w320/rw.png" },
  { "name": "Samoa", "iso2": "ws", "dialCode": "+685", "flag": "https://flagcdn.com/w320/ws.png" },
  { "name": "Saudi Arabia", "iso2": "sa", "dialCode": "+966", "flag": "https://flagcdn.com/w320/sa.png" },
  { "name": "Senegal", "iso2": "sn", "dialCode": "+221", "flag": "https://flagcdn.com/w320/sn.png" },
  { "name": "Serbia", "iso2": "rs", "dialCode": "+381", "flag": "https://flagcdn.com/w320/rs.png" },
  { "name": "Seychelles", "iso2": "sc", "dialCode": "+248", "flag": "https://flagcdn.com/w320/sc.png" },
  { "name": "Sierra Leone", "iso2": "sl", "dialCode": "+232", "flag": "https://flagcdn.com/w320/sl.png" },
  { "name": "Singapore", "iso2": "sg", "dialCode": "+65", "flag": "https://flagcdn.com/w320/sg.png" },
  { "name": "Slovakia", "iso2": "sk", "dialCode": "+421", "flag": "https://flagcdn.com/w320/sk.png" },
  { "name": "Slovenia", "iso2": "si", "dialCode": "+386", "flag": "https://flagcdn.com/w320/si.png" },
  { "name": "Somalia", "iso2": "so", "dialCode": "+252", "flag": "https://flagcdn.com/w320/so.png" },
  { "name": "South Africa", "iso2": "za", "dialCode": "+27", "flag": "https://flagcdn.com/w320/za.png" },
  { "name": "South Korea", "iso2": "kr", "dialCode": "+82", "flag": "https://flagcdn.com/w320/kr.png" },
  { "name": "Spain", "iso2": "es", "dialCode": "+34", "flag": "https://flagcdn.com/w320/es.png" },
  { "name": "Sri Lanka", "iso2": "lk", "dialCode": "+94", "flag": "https://flagcdn.com/w320/lk.png" },
  { "name": "Sudan", "iso2": "sd", "dialCode": "+249", "flag": "https://flagcdn.com/w320/sd.png" },
  { "name": "Sweden", "iso2": "se", "dialCode": "+46", "flag": "https://flagcdn.com/w320/se.png" },
  { "name": "Switzerland", "iso2": "ch", "dialCode": "+41", "flag": "https://flagcdn.com/w320/ch.png" },
  { "name": "Syria", "iso2": "sy", "dialCode": "+963", "flag": "https://flagcdn.com/w320/sy.png" },
  { "name": "Taiwan", "iso2": "tw", "dialCode": "+886", "flag": "https://flagcdn.com/w320/tw.png" },
  { "name": "Tajikistan", "iso2": "tj", "dialCode": "+992", "flag": "https://flagcdn.com/w320/tj.png" },
  { "name": "Tanzania", "iso2": "tz", "dialCode": "+255", "flag": "https://flagcdn.com/w320/tz.png" },
  { "name": "Thailand", "iso2": "th", "dialCode": "+66", "flag": "https://flagcdn.com/w320/th.png" },
  { "name": "Togo", "iso2": "tg", "dialCode": "+228", "flag": "https://flagcdn.com/w320/tg.png" },
  { "name": "Trinidad and Tobago", "iso2": "tt", "dialCode": "+1", "flag": "https://flagcdn.com/w320/tt.png" },
  { "name": "Tunisia", "iso2": "tn", "dialCode": "+216", "flag": "https://flagcdn.com/w320/tn.png" },
  { "name": "Turkey", "iso2": "tr", "dialCode": "+90", "flag": "https://flagcdn.com/w320/tr.png" },
  { "name": "Turkmenistan", "iso2": "tm", "dialCode": "+993", "flag": "https://flagcdn.com/w320/tm.png" },
  { "name": "Uganda", "iso2": "ug", "dialCode": "+256", "flag": "https://flagcdn.com/w320/ug.png" },
  { "name": "Ukraine", "iso2": "ua", "dialCode": "+380", "flag": "https://flagcdn.com/w320/ua.png" },
  { "name": "United Arab Emirates", "iso2": "ae", "dialCode": "+971", "flag": "https://flagcdn.com/w320/ae.png" },
  { "name": "United Kingdom", "iso2": "gb", "dialCode": "+44", "flag": "https://flagcdn.com/w320/gb.png" },
  { "name": "United States", "iso2": "us", "dialCode": "+1", "flag": "https://flagcdn.com/w320/us.png" },
  { "name": "Uruguay", "iso2": "uy", "dialCode": "+598", "flag": "https://flagcdn.com/w320/uy.png" },
  { "name": "Uzbekistan", "iso2": "uz", "dialCode": "+998", "flag": "https://flagcdn.com/w320/uz.png" },
  { "name": "Venezuela", "iso2": "ve", "dialCode": "+58", "flag": "https://flagcdn.com/w320/ve.png" },
  { "name": "Vietnam", "iso2": "vn", "dialCode": "+84", "flag": "https://flagcdn.com/w320/vn.png" },
  { "name": "Yemen", "iso2": "ye", "dialCode": "+967", "flag": "https://flagcdn.com/w320/ye.png" },
  { "name": "Zambia", "iso2": "zm", "dialCode": "+260", "flag": "https://flagcdn.com/w320/zm.png" },
  { "name": "Zimbabwe", "iso2": "zw", "dialCode": "+263", "flag": "https://flagcdn.com/w320/zw.png" }
]
